version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: my-postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
